namespace = EFMIv1


; ------------------------------------------------------------------------------
; - GLOBAL CONFIG CONSTANTS
; ------------------------------------------------------------------------------

[Constants]
global locked $cfg_instance_config_byte_size = 16 * 4 * 4


; ------------------------------------------------------------------------------
; - SHAPE KEYS API
; ------------------------------------------------------------------------------

; EFMI Tools exports `mod.ini` with dedicated `CommandListSetShapeKey`.
;
; Usage example (set `Component 0` `Shape Key 0` value to `0.5`):
;
; $component_id = 0
; $shapekey_id = 0
; $shapekey_value = 0.5
; local $shapekey_0_value
; if $shapekey_0_value != $shapekey_value
;     run = CommandListSetShapeKey
;     $shapekey_0_value = $shapekey_value
; endif
;
; For optimization purposes, we want to run `CommandListSetShapeKey` only when shapekey value was changed.
; So we:
;   * Declare dedicated `local $shapekey_0_value` for `Shape Key 0` to remember its last set value.
;   * Compare values and do `run` only on values mismatch, afterwards we update `$shapekey_0_value` with new value.


; ------------------------------------------------------------------------------
; - OBJECT API - READ CONFIG
; ------------------------------------------------------------------------------

[CommandListObject_ReadConfig]
; Just a dummy for now, but mods should call it after setting object-wide data.

; CommandListObject_ReadConfig INPUT

[Constants]
global $bones_count = 0
global $component_count = 0
global $instance_count = 8
global $custom_mesh_scale = 1.0


; ------------------------------------------------------------------------------
; - COMPONENT API - READ CONFIG
; ------------------------------------------------------------------------------

[ResourceOriginal_VS_CB_Temp]

[CommandListComponent_ReadConfig]
if vs-cb2->Size / 16 == 4096
    $instance_config_vs_cb_slot = 2
    $instance_config_vs_cb_byte_offset = vs-cb2->Offset
    ResourceOriginal_VS_CB = ref vs-cb2
elif vs-cb1->Size / 16 == 4096
    $instance_config_vs_cb_slot = 1
    $instance_config_vs_cb_byte_offset = vs-cb1->Offset
    ResourceOriginal_VS_CB = ref vs-cb1
elif vs-cb3->Size / 16 == 4096
    $instance_config_vs_cb_slot = 3
    $instance_config_vs_cb_byte_offset = vs-cb3->Offset
    ResourceOriginal_VS_CB = ref vs-cb3
else
    $instance_config_vs_cb_slot = -1
endif

if ps-cb2->Size / 16 == 4096
    $instance_config_ps_cb_slot = 2
    $instance_config_ps_cb_byte_offset = ps-cb2->Offset
    ResourceOriginal_PS_CB = ref ps-cb2
elif ps-cb1->Size / 16 == 4096
    $instance_config_ps_cb_slot = 1
    $instance_config_ps_cb_byte_offset = ps-cb1->Offset
    ResourceOriginal_PS_CB = ref ps-cb1
else
    $instance_config_ps_cb_slot = -1
endif

; CommandListComponent_ReadConfig INPUT

[Constants]
global $component_id = 0
global $gpu_posed = 0
global $lod_level = 0

; CommandListComponent_ReadConfig OUTPUT

[ResourceOriginal_VS_CB]

[ResourceOriginal_PS_CB]

[Constants]
global $instance_config_vs_cb_slot = 0
global $instance_config_vs_cb_byte_offset = 0

global $instance_config_ps_cb_slot = 0
global $instance_config_ps_cb_byte_offset = 0


; ------------------------------------------------------------------------------
; - COMPONENT API - SET INSTANCE CONFIG
; ------------------------------------------------------------------------------

[CommandListComponent_SetInstanceConfig_VS]
if $draw_call_instance_id > 0
    if $instance_config_vs_cb_slot == 2
        vs-cb2 = ref ResourceOriginal_VS_CB->Region($instance_config_vs_cb_byte_offset + $draw_call_instance_id * $cfg_instance_config_byte_size, $cfg_instance_config_byte_size)
    else if $instance_config_vs_cb_slot == 1
        vs-cb1 = ref ResourceOriginal_VS_CB->Region($instance_config_vs_cb_byte_offset + $draw_call_instance_id * $cfg_instance_config_byte_size, $cfg_instance_config_byte_size)
    else if $instance_config_vs_cb_slot == 3
        vs-cb3 = ref ResourceOriginal_VS_CB->Region($instance_config_vs_cb_byte_offset + $draw_call_instance_id * $cfg_instance_config_byte_size, $cfg_instance_config_byte_size)
    endif
endif


[CommandListComponent_SetInstanceConfig_PS]
if $draw_call_instance_id > 0
    if $instance_config_ps_cb_slot == 2
        ps-cb2 = ref ResourceOriginal_PS_CB->Region($instance_config_ps_cb_byte_offset + $draw_call_instance_id * $cfg_instance_config_byte_size, $cfg_instance_config_byte_size)
    else if $instance_config_ps_cb_slot == 1
        ps-cb1 = ref ResourceOriginal_PS_CB->Region($instance_config_ps_cb_byte_offset + $draw_call_instance_id * $cfg_instance_config_byte_size, $cfg_instance_config_byte_size)
    endif
endif


; ------------------------------------------------------------------------------
; - COMPONENT API - OVERRIDE TEXTURES
; ------------------------------------------------------------------------------

; Applies custom textures to mesh
; Triggers TextureOverride sections for PS slots from 0 to 22
; If hash value of TextureOverride matches `hash` of resource in slot, TextureOverride puts defined custom texture Resource in `this` slot
[CommandListOverrideTextures]
CheckTextureOverride = ps-t0
CheckTextureOverride = ps-t1
CheckTextureOverride = ps-t2
CheckTextureOverride = ps-t3
CheckTextureOverride = ps-t4
CheckTextureOverride = ps-t5
CheckTextureOverride = ps-t6
CheckTextureOverride = ps-t7
CheckTextureOverride = ps-t8
CheckTextureOverride = ps-t9
CheckTextureOverride = ps-t10
CheckTextureOverride = ps-t11
CheckTextureOverride = ps-t12
CheckTextureOverride = ps-t13
CheckTextureOverride = ps-t14
CheckTextureOverride = ps-t15
CheckTextureOverride = ps-t16
CheckTextureOverride = ps-t17
CheckTextureOverride = ps-t18
CheckTextureOverride = ps-t19
CheckTextureOverride = ps-t20
CheckTextureOverride = ps-t21
CheckTextureOverride = ps-t22


; TODO: Extend DLL INI syntax to support:
; [CommandListOverrideTexturesRecursive]
; if ps->srv_type($slot_id) > 0
;     CheckTextureOverride = ps-t[$slot_id]
; endif
; $slot_id = $slot_id + 1
; if $slot_id <= $last_slot_id
;     run = CommandListOverrideTexturesRecursive
; endif

; [CommandListOverrideTextures]
; $slot_id = ps->srv_first_slot()
; $last_slot_id = ps->srv_last_slot()
; run = CommandListOverrideTexturesRecursive


; ------------------------------------------------------------------------------
; - COMPONENT API - DRAW CALL
; ------------------------------------------------------------------------------

[Constants]
global $merged_skeleton_connected = 0

[CommandListComponent_Instance_DrawOriginal]
if $PoolSpatialIdentity_IdentifiedInstances[$draw_call_instance_id] == $enum_override_type_original
    drawindexedinstanced = INDEX_COUNT, 1, 0, 0, $draw_call_instance_id
endif


[CommandListCallback_Component_DrawCustom]

[CommandList_Component_Instance_DrawCustom]
if $PoolSpatialIdentity_IdentifiedInstances[$draw_call_instance_id] == $enum_override_type_custom
    if $merged_skeleton_connected
        run = CommandListMergedSkeleton_Apply
    else
        run = CommandListComponent_SetInstanceConfig_VS
        run = CommandListComponent_SetInstanceConfig_PS
    endif
    run = CommandListCallback_Component_DrawCustom
endif


[CommandListCallback_MergedSkeleton_ConnectComponent]


[CommandListComponent_DrawInstances]

if $draw_call_has_unknown_instance
    CommandListCallback_OnInstance = ref CommandListComponent_Instance_DrawOriginal
    run = CommandListIterateInstances
endif

if $draw_call_has_modded_instance
    if $gpu_posed
        run = CommandListCallback_MergedSkeleton_ConnectComponent
        if @ResourceOutput_MergedSkeleton != 0
            run = CommandListMergedSkeleton_DetectBoneDataSource
            if $bones_data_source != 0
                $merged_skeleton_connected = 1
            else
                ResourceOutput_MergedSkeleton = null
                CommandListCallback_MergedSkeleton_ConnectComponent = null
            endif
        endif
    endif
    CommandListCallback_OnInstance = ref CommandList_Component_Instance_DrawCustom
    run = CommandListIterateInstances
endif

if $merged_skeleton_connected
    ResourceOutput_MergedSkeleton = null
    CommandListCallback_MergedSkeleton_ConnectComponent = null
    $merged_skeleton_connected = 0
    $skip_skeleton_override = 0
elif !$gpu_posed
    CommandListCallback_MergedSkeleton_ConnectComponent = null
endif


[CommandListComponent_DrawInstances_NoDecomposition]
run = CommandListCallback_Component_DrawCustom


; ------------------------------------------------------------------------------
; - TEXT PRINTER API
; ------------------------------------------------------------------------------

; Prints text on screen using provided params
[CommandListPrintText]
; Input:
; Resource\EFMIv1\Text
; Resource\EFMIv1\TextParams
;
; Usage example (resource formats are listed below):
; Resource\EFMIv1\Text = ref ResourceMyText
; Resource\EFMIv1\TextParams = ref ResourceMyTextParams
; run = CommandList\EFMIv1\PrintText
run = CommandListRenderText


; Text string example resource printable by CommandListPrintText
[ResourceTextExample]
type = Buffer
data = "Hello World!"


; Text file example resource printable by CommandListPrintText
[ResourceTextFileExample]
type = buffer
format = R8_UINT
filename = MyText.txt


; Text params example resource for CommandListPrintText
; Using these parameter buffers as a way to pass in constant parameters without
; taking up any of the IniParams slots while still allowing the parameters to
; be customised on a per-message basis.
[ResourceTextParamsExample]
type = StructuredBuffer
array = 1
data = R32_FLOAT  -0.25 +0.15 +0.25 -0.05   1.00 1.00 1.00 1.00   0.00 0.00 0.00 0.95   0.02  0.05   2 1   1   1.0
;                x1-^  y1-^  x2-^  y2-^   | R-^  G-^  B-^  A-^  | R-^  G-^  B-^  A-^  | ^-H    V-^ | ^ ^ | ^- text alignment: 0=left 1=center 2=right | ^- font scale
;                Rectangle (range -1:+1)  | Text Color          | Background Color    | Border     |  ^- h/v-anchor: 0=none 1=left/top 2=center 3=right/bottom 
