namespace=EFMIv1


; ------------------------------------------------------------------------------
; - DRAW CALL INSTANCES ITERATION
; ------------------------------------------------------------------------------

[Constants]
global $draw_call_instance_id = 0

[CommandListCallback_OnInstance]

[CommandListIterateInstances]
$draw_call_instance_id = 0
run = CommandList_IterateInstancesRecursive_Internal

[CommandList_IterateInstancesRecursive_Internal]
run = CommandListCallback_OnInstance
$draw_call_instance_id = $draw_call_instance_id + 1
if $draw_call_instance_id < INSTANCE_COUNT
    run = CommandList_IterateInstancesRecursive_Internal
endif


; ------------------------------------------------------------------------------
; - INI PARAMS BACKUP/RESTORE
; ------------------------------------------------------------------------------

[Constants]
global $bak_x0 = 0
global $bak_y0 = 0
global $bak_z0 = 0
global $bak_w0 = 0
global $bak_x1 = 0
global $bak_y1 = 0
global $bak_z1 = 0
global $bak_w1 = 0

[CommandListBackupIniParams0]
$bak_x0 = x0
$bak_y0 = y0
$bak_z0 = z0
$bak_w0 = w0

[CommandListRestoreIniParams0]
x0 = $bak_x0
y0 = $bak_y0
z0 = $bak_z0
w0 = $bak_w0

[CommandListBackupIniParams1]
$bak_x1 = x1
$bak_y1 = y1
$bak_z1 = z1
$bak_w1 = w1

[CommandListRestoreIniParams1]
x1 = $bak_x1
y1 = $bak_y1
z1 = $bak_z1
w1 = $bak_w1
