namespace=EFMIv1


; ------------------------------------------------------------------------------
; - GLOBAL CONFIG CONSTANTS
; ------------------------------------------------------------------------------

[Constants]
global locked $cfg_ms_max_lod_level_count = 4
global locked $cfg_ms_implicit_bones_count = 512
global locked $cfg_ms_skeletons_count = 2
global locked $cfg_ms_bone_entry_size = 3


[Constants]
global $merged_skeleton_offset = 0
global $merged_skeleton_instance_id = 0


; ------------------------------------------------------------------------------
; - INITIALIZE MERGED SKELETON BUFFER
; ------------------------------------------------------------------------------

[CommandListInitializeMergedSkeleton]
run = CustomShader\EFMIv1\MergedSkeletonInitializer


; ------------------------------------------------------------------------------
; - ATTACH COMPONENT
; ------------------------------------------------------------------------------

[CommandListMergedSkeleton_AttachComponent]
$component_vg_offset = $PoolInput_MergedSkeleton_Component_VertexGroupOffsets[$component_id]
$component_vg_count = $PoolInput_MergedSkeleton_Component_VertexGroupCounts[$component_id]

ResourceInput_ComponentBoneMatrices = ref vs-t0

; CommandListMergedSkeleton_AttachComponent INPUT

[PoolInput_MergedSkeleton_Component_VertexGroupOffsets]
[PoolInput_MergedSkeleton_Component_VertexGroupCounts]

[PoolInput_MergedSkeleton_Instance_UpdateFrame]
[PoolInput_MergedSkeleton_Instance_LodLevel]

; CommandListMergedSkeleton_AttachComponent OUTPUT

[ResourceInput_ComponentBoneMatrices]

[Constants]
global $component_vg_offset = 0
global $component_vg_count = 0


; ------------------------------------------------------------------------------
; - IMPORT COMPONENT BONES
; ------------------------------------------------------------------------------

[CommandListMergedSkeleton_ImportComponentInstanceBones]
if $bones_data_source == $enum_bones_source_vs_t0
    run = CustomShader_MergedSkeleton_BonesImporter_RollingBuffer
else
    run = CustomShader_MergedSkeleton_BonesImporter_ConstantBuffer
endif


; ------------------------------------------------------------------------------
; - OVERRIDE COMPONENT SKELETON
; ------------------------------------------------------------------------------

[Resource_Component_Instance_ConfigRW]
type = RWBuffer
format = R32G32B32A32_FLOAT
; 16 x R32G32B32A32_FLOAT constants per instance
array = 16

[ResourceConfigWithBones]

[CommandListMergedSkeleton_OverrideComponentSkeleton]

if $skip_skeleton_override
    ; Move instance config VS CB window to current instance.
    run = CommandListComponent_SetInstanceConfig_VS

elif $bones_data_source == $enum_bones_source_vs_t0

    cs-u0 = ref Resource_Component_Instance_ConfigRW

    run = CustomShader_MergedSkeleton_InstanceConfigOverrider_RollingBuffer

    ; Override instance config VS CB with one containing offsets to merged skeleton buffer.
    if $instance_config_vs_cb_slot == 2
        vs-cb2 = copy Resource_Component_Instance_ConfigRW
    else if $instance_config_vs_cb_slot == 1
        vs-cb1 = copy Resource_Component_Instance_ConfigRW
    else if $instance_config_vs_cb_slot == 3
        vs-cb3 = copy Resource_Component_Instance_ConfigRW
    endif

    vs-t0 = ref ResourceOutput_MergedSkeleton

else 
    ; Move instance config VS CB window to current instance.
    run = CommandListComponent_SetInstanceConfig_VS

    ResourceConfigWithBones = copy ResourceOutput_MergedSkeleton->Region($merged_skeleton_offset * 16 - 16 * 4, $bones_count * $cfg_ms_bone_entry_size * 16 + 16 * 4)
    cs-u0 = ref ResourceConfigWithBones

    run = CustomShader_MergedSkeleton_InstanceConfigOverrider_ConstantBuffer

    if $bones_data_source == $enum_bones_source_cb3
        vs-cb3 = copy ResourceConfigWithBones
    elif $bones_data_source == $enum_bones_source_cb4
        vs-cb4 = copy ResourceConfigWithBones
    endif

endif

; Move instance config PS CB window to current instance.
run = CommandListComponent_SetInstanceConfig_PS


; ------------------------------------------------------------------------------
; - UPDATE MERGED SKELETON
; ------------------------------------------------------------------------------

[Constants]
global locked $enum_bones_source_vs_t0 = 1
global locked $enum_bones_source_cb3 = 2
global locked $enum_bones_source_cb4 = 3
global $bones_data_source = 0
global $skip_skeleton_override = 0


[CommandListMergedSkeleton_DetectBoneDataSource]
if vs->srv_stride(0) == 16 && $instance_config_vs_cb_slot != -1
    ; The most common skeleton delivery path. Bone data offsets are supplied via vs-cb1/2/3, bone data entries via vs-t0.
    $bones_data_source = $enum_bones_source_vs_t0
elif vs->cb_size(4) == 4096
    ; Sometimes used for FX shaders. Both bone data offsets and bone data entries are supplied via vs-cb4.
    $bones_data_source = $enum_bones_source_cb4
elif vs->cb_size(3) == 4096
    ; Sometimes used for FX shaders. Both bone data offsets and bone data entries are supplied via vs-cb3.
    $bones_data_source = $enum_bones_source_cb3
else
    ; Mesh uses unknown posing method. We should avoid messing with it.
    $bones_data_source = 0
endif


[CommandListMergedSkeleton_Apply]

if $bones_data_source == $enum_bones_source_vs_t0
    cs-cb0 = ref ResourceOriginal_VS_CB->Region($instance_config_vs_cb_byte_offset + $draw_call_instance_id * $cfg_instance_config_byte_size, $cfg_instance_config_byte_size)
elif $bones_data_source == $enum_bones_source_cb4
    cs-cb0 = ref vs-cb4->Region(vs-cb4->Offset, vs-cb4->Size)
elif $bones_data_source == $enum_bones_source_cb3
    cs-cb0 = ref vs-cb3->Region(vs-cb3->Offset, vs-cb3->Size)
endif

$merged_skeleton_instance_id = $PoolSpatialIdentity_SpatialIds[$draw_call_instance_id]

$merged_skeleton_offset = ($cfg_ms_implicit_bones_count + $cfg_ms_skeletons_count * $bones_count * $merged_skeleton_instance_id) * $cfg_ms_bone_entry_size

local $instance_data_index = $component_id * $instance_count + $merged_skeleton_instance_id
local $instance_update_frame = $PoolInput_MergedSkeleton_Instance_UpdateFrame[$instance_data_index]

if $instance_update_frame != FRAME_NUMBER
    ; Limit bones import to 1 time per frame for each component.
    $PoolInput_MergedSkeleton_Instance_UpdateFrame[$instance_data_index] = FRAME_NUMBER
    $PoolInput_MergedSkeleton_Instance_LodLevel[$instance_data_index] = $lod_level
    run = CommandListMergedSkeleton_ImportComponentInstanceBones
else
    ; If component's skeleton was already imported in current frame...
    local $instance_lod_level = $PoolInput_MergedSkeleton_Instance_LodLevel[$instance_data_index]
    if  $lod_level < $instance_lod_level
        ; ... but we got lower level LoD, import better quality skeleton from it.
        $PoolInput_MergedSkeleton_Instance_LodLevel[$instance_data_index] = $lod_level
        run = CommandListMergedSkeleton_ImportComponentInstanceBones
    endif
endif

; Replace component's skeleton data with merged skeleton data.
run = CommandListMergedSkeleton_OverrideComponentSkeleton


; ------------------------------------------------------------------------------
; - SHADER - BONE DATA INITIALIZER
; ------------------------------------------------------------------------------

[ResourceOutputMergedSkeleton_Template]

[CustomShaderMergedSkeletonInitializer]
; Specify shader.
cs = Shaders/MergedSkeleton_BoneDataInitializer.hlsl

; Pass resources to the shader.
; * MergedSkeletonRW
cs-u0 = ref ResourceOutputMergedSkeleton_Template
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = ($cfg_ms_implicit_bones_count+64-1)/64, 1, 1

; Unbind resources.
cs-u0 = null


; ------------------------------------------------------------------------------
; - SHADER - BONE DATA IMPORTER - ROLLING BUFFER
; ------------------------------------------------------------------------------


[PoolInput_MergedSkeleton_Component_LodRemaps]

[ResourceOutput_MergedSkeleton]

[CustomShader_MergedSkeleton_BonesImporter_RollingBuffer]
; Specify shader.
cs = Shaders/MergedSkeleton_BoneDataImporter_RollingBuffer.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0
run = CommandListBackupIniParams1

; Pass resources to the shader.
; * InstanceConfigCB
; cs-cb0 (set by CommandListMergedSkeleton_Apply)
; * ComponentBoneMatrices
cs-t0 = ref ResourceInput_ComponentBoneMatrices
; * OriginalComponentLODRemap
cs-t1 = ref PoolInput_MergedSkeleton_Component_LodRemaps[$component_id * $cfg_ms_max_lod_level_count + $lod_level]
; * MergedSkeletonRW
cs-u0 = ref ResourceOutput_MergedSkeleton
; * DebugRW
; cs-u7 = ResourceDebugRW

; Pass INI variables to the shader.
; * ComponentVertexGroupOffset
x0 = $component_vg_offset
; * ComponentVertexGroupCount
y0 = $component_vg_count
; * UseOriginalComponentLODRemap
z0 = @cs-t1 != 0
; * CustomComponentMeshScale
w0 = $custom_mesh_scale
; * InstanceConfigOffset
x1 = 5
; * MergedSkeletonOffset
y1 = $merged_skeleton_offset
; * MergedSkeletonEntriesCount
z1 = $bones_count * $cfg_ms_bone_entry_size

; Run the compute shader.
dispatch = ($component_vg_count+64-1)/64, 1, 1

; Unbind resources.
cs-u0 = null

; Restore IniParams.
run = CommandListRestoreIniParams0
run = CommandListRestoreIniParams1


; ------------------------------------------------------------------------------
; - SHADER - BONE DATA IMPORTER - CONSTANT BUFFER (WITH BONES)
; ------------------------------------------------------------------------------

[CustomShader_MergedSkeleton_BonesImporter_ConstantBuffer]
; Specify shader.
cs = Shaders/MergedSkeleton_BoneDataImporter_ConstantBuffer.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0
run = CommandListBackupIniParams1

; Pass resources to the shader.
; * InstanceConfigWithBonesCB
; cs-cb0 (set by CommandListMergedSkeleton_Apply)
; * OriginalComponentLODRemap
cs-t1 = ref PoolInput_MergedSkeleton_Component_LodRemaps[$component_id * $cfg_ms_max_lod_level_count + $lod_level]
; * MergedSkeletonRW
cs-u0 = ref ResourceOutput_MergedSkeleton
; * DebugRW
; cs-u7 = ResourceDebugRW

; Pass INI variables to the shader.
; * ComponentVertexGroupOffset
x0 = $component_vg_offset
; * ComponentVertexGroupCount
y0 = $component_vg_count
; * UseOriginalComponentLODRemap
z0 = @cs-t1 != 0
; * CustomComponentMeshScale
w0 = $custom_mesh_scale
; * InstanceConfigOffset
x1 = 0
; * MergedSkeletonOffset
y1 = $merged_skeleton_offset
; * MergedSkeletonEntriesCount
z1 = $bones_count * $cfg_ms_bone_entry_size

; Run the compute shader.
dispatch = ($component_vg_count+64-1)/64, 1, 1

; Unbind resources.
cs-u0 = null

; Restore IniParams.
run = CommandListRestoreIniParams0
run = CommandListRestoreIniParams1


; ------------------------------------------------------------------------------
; - SHADER - INSTANCE CONFIG OVERRIDER - ROLLING BUFFER
; ------------------------------------------------------------------------------

[CustomShader_MergedSkeleton_InstanceConfigOverrider_RollingBuffer]
; Specify shader.
cs = Shaders/MergedSkeleton_InstanceConfigOverrider_RollingBuffer.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0

; Pass INI variables to the shader.
; * MergedSkeletonOffset
x0 = $merged_skeleton_offset - 3
; * InputInstanceConfigOffset
y0 = 0
; * OutputInstanceConfigOffset
z0 = 0
; * MergedSkeletonEntriesCount
w0 = $bones_count * $cfg_ms_bone_entry_size

; Pass resources to the shader.
; * InstanceConfigRW
; cs-u0
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = 1, 1, 1

; Unbind resources.
cs-u0 = null

; Restore IniParams.
run = CommandListRestoreIniParams0


; ------------------------------------------------------------------------------
; - SHADER - INSTANCE CONFIG OVERRIDER - CONSTANT BUFFER (WITH BONES)
; ------------------------------------------------------------------------------

[CustomShader_MergedSkeleton_InstanceConfigOverrider_ConstantBuffer]
; Specify shader.
cs = Shaders/MergedSkeleton_InstanceConfigOverrider_ConstantBuffer.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0

; Pass INI variables to the shader.
; * MergedSkeletonOffset
x0 = $merged_skeleton_offset - 3
; * InputInstanceConfigOffset
y0 = 0
; * OutputInstanceConfigOffset
z0 = 0
; * MergedSkeletonEntriesCount
w0 = $bones_count * $cfg_ms_bone_entry_size

; Pass resources to the shader.
; * InstanceConfigRW
; cs-u0
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = 1, 1, 1

; Unbind resources.
cs-u0 = null

; Restore IniParams.
run = CommandListRestoreIniParams0
