namespace=EFMIv1


; Constants -------------------------

[Constants]

global $shapekey_id = 0
global $shapekey_value = 0

global $shapekey = 0
global $mesh_vertex_count = 0
global $mesh_vertex_offset = 0

global $shapekey_batch_id = 0
global $shapekey_batch_vertex_offset = 0
global $shapekey_batch_vertex_count = 0

global $input_position_stride = 0
global $output_position_stride = 0

global $position_quantization_scale_x = 0
global $position_quantization_scale_y = 0
global $position_quantization_scale_z = 0


; Shape Keys Shaders -------------------------

; Writes custom shape key values to output buffer.
[CustomShaderShapeKeySetter]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/SkapeKeySetter.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
run = CommandListBackupIniParams0
; Pass variables to the shader
x0 = $shapekey_id
y0 = $shapekey_value
; Pass resources to the shader
cs-u3 = ref ResourceOutput_ShapeKeyValues
; cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = 1, 1, 1
; Unbind resources
cs-u3 = null
; Restore IniParams:
run = CommandListRestoreIniParams0


; Accumulates INT32-quantized xyz position deltas in output buffer.
[CustomShaderShapeKeyLoader]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyLoader.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
run = CommandListBackupIniParams0
; Pass variables to the shader
; ShapeKeyBatchID
x0 = $shapekey_batch_id
; Pass resources to the shader
cs-t0 = ref ResourceInput_ShapeKeyBatchConfigs
cs-t1 = ref ResourceInput_ShapeKeyVertexIds
cs-t2 = ref ResourceInput_ShapeKeyVertexOffsets
cs-u3 = ref ResourceInput_ShapeKeyValues
cs-u0 = ref ResourceOutput_QuantizedShapeKeyDeltas
;cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = $shapekey_batch_vertex_count/32+1, 1, 1
; Unbind resources
cs-u0 = null
cs-u3 = null
; Restore IniParams:
run = CommandListRestoreIniParams0


[CommandListLoadCustomShapeKeysBatch]
run = CustomShaderShapeKeyLoader


; Dequantizes INT32-quantized xyz position deltas to FLOAT32.
; Outputs vertex position buffer with applied deltas (morphed mesh).
[CustomShaderShapeKeyDequantizer]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyDequantizer.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
run = CommandListBackupIniParams0
; Pass variables to the shader
; VertexOffset
x0 = $shapekey
; VertexCount
y0 = $mesh_vertex_count
; SourceVertexFloatsCount
z0 = $input_position_stride / 4
; DestinationVertexFloatsCount
w0 = $output_position_stride / 4
; Pass resources to the shader
cs-t0 = ref ResourceInput_ShapeKeyBatchConfigs
cs-t1 = ref ResourceInput_VertexPositions
cs-u0 = ref ResourceInput_QuantizedShapeKeyDeltas
cs-u2 = ref ResourceOutput_ShapeKeyedPositions
;cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = $mesh_vertex_count/64+1, 1, 1
; Unbind resources
cs-u0 = null
cs-u2 = null
; Restore IniParams:
run = CommandListRestoreIniParams0


[CommandListDequantizeCustomShapeKeys]
$input_position_stride = ResourceInput_VertexPositions->SourceStride
$output_position_stride = ResourceOutput_ShapeKeyedPositions->SourceStride
$shapekey = 0
$mesh_vertex_count = ResourceInput_VertexPositions->Size / $input_position_stride
if $mesh_vertex_count > 0
    run = CustomShaderShapeKeyDequantizer
endif


; Copies float3 vertex positions between buffers with differing strides.
[CustomShaderShapeKeyedPositionCopier]
; Load shader and explicitly unbind other shaders for safety
cs = Shaders/ShapeKeyedPositionCopier.hlsl
vs = null
ps = null
hs = null
ds = null
gs = null
; Backup used IniParams
run = CommandListBackupIniParams0
; Pass variables to the shader
; VertexOffset
x0 = $mesh_vertex_offset
; VertexCount
y0 = $mesh_vertex_count
; SourceVertexFloatsCount
z0 = $input_position_stride / 4
; DestinationVertexFloatsCount
w0 = $output_position_stride / 4
; Pass resources to the shader
cs-t0 = ref ResourceInput_ShapeKeyedPositions
cs-u0 = ref ResourceOutput_ShapeKeyedPositions
; cs-u7 = ResourceDebugRW
; Run the compute shader
dispatch = $mesh_vertex_count/64+1, 1, 1
; Unbind resources
cs-u0 = null
; Restore IniParams:
run = CommandListRestoreIniParams0


[CommandListCopyShapeKeyedPosition]
$input_position_stride = ResourceInput_ShapeKeyedPositions->SourceStride
$output_position_stride = ResourceOutput_ShapeKeyedPositions->SourceStride
$mesh_vertex_offset = 0
$mesh_vertex_count = ResourceInput_ShapeKeyedPositions->Size / $input_position_stride
if $mesh_vertex_count > 0
    run = CustomShaderShapeKeyedPositionCopier
endif


; Resources -------------------------

[ResourceInput_ShapeKeyValues]

[ResourceInput_ShapeKeyBatchConfigs]
[ResourceInput_ShapeKeyVertexIds]
[ResourceInput_ShapeKeyVertexOffsets]

[ResourceInput_VertexPositions]
[ResourceInput_QuantizedShapeKeyDeltas]
[ResourceInput_ShapeKeyedPositions]

[ResourceOutput_ShapeKeyValues]
[ResourceOutput_QuantizedShapeKeyDeltas]
[ResourceOutput_ShapeKeyedPositions]


; Helpers -------------------------

[Constants]
global $bak_x0 = 0
global $bak_y0 = 0
global $bak_z0 = 0
global $bak_w0 = 0
global $bak_x1 = 0
global $bak_y1 = 0
global $bak_z1 = 0
global $bak_w1 = 0

[CommandListBackupIniParams0]
$bak_x0 = x0
$bak_y0 = y0
$bak_z0 = z0
$bak_w0 = w0

[CommandListRestoreIniParams0]
x0 = $bak_x0
y0 = $bak_y0
z0 = $bak_z0
w0 = $bak_w0

[CommandListBackupIniParams1]
$bak_x1 = x1
$bak_y1 = y1
$bak_z1 = z1
$bak_w1 = w1

[CommandListRestoreIniParams1]
x1 = $bak_x1
y1 = $bak_y1
z1 = $bak_z1
w1 = $bak_w1
