namespace=EFMIv1


; ------------------------------------------------------------------------------
; - GLOBAL CONFIG CONSTANTS
; ------------------------------------------------------------------------------

[Constants]
global locked $cfg_sk_batch_size = 127
global locked $cfg_sk_max_batch_count = 100
global locked $cfg_sk_max_lod_level_count = 10


; ------------------------------------------------------------------------------
; - ATTACH COMPONENT
; ------------------------------------------------------------------------------

[PoolInput_ShapeKeys_LodPositionCount]
[PoolInput_ShapeKeys_BatchCount]
[PoolInput_ShapeKeys_BatchVertexCount]
[PoolInput_ShapeKeys_BatchConfigs]

[PoolInput_ShapeKeys_VertexIds]
[PoolInput_ShapeKeys_VertexOffsets]
[PoolInput_ShapeKeys_VertexPositions]

[PoolInput_ShapeKeyValues]
[PoolInput_ShapeKeys_MorphedPositions]

[CommandListCallback_ShapeKeys_AttachComponent]


; ------------------------------------------------------------------------------
; - PROCESS BATCHES
; ------------------------------------------------------------------------------

[CommandList_ShapeKeys_ProcessBatch]
$shapekey_batch_id = $component_shapekey_batch_id
local $shapekeyed_batch_uid = $component_id * $cfg_sk_max_batch_count + $shapekey_batch_id
$shapekey_batch_vertex_count = $PoolInput_ShapeKeys_BatchVertexCount[$shapekeyed_batch_uid]
; Contains position deltas quantisation scales and per-batch configs.
ResourceInput_ShapeKeyBatchConfigs = ref PoolInput_ShapeKeys_BatchConfigs[$component_id]
; Contains IDs of vertices affected by shapekeys.
ResourceInput_ShapeKeyVertexIds = ref PoolInput_ShapeKeys_VertexIds[$component_id]
; Contains per-vertex XYZ position deltas calculated for max shapekey value (1.0).
ResourceInput_ShapeKeyVertexOffsets = ref PoolInput_ShapeKeys_VertexOffsets[$component_id]
; Contains shapekey values configured via CommandListSetShapeKey.
ResourceInput_ShapeKeyValues = ref PoolInput_ShapeKeyValues[$component_id]
; Stores summed per-vertex weighted XYZ positions deltas quantized to INT32 (temporary data).
ResourceOutput_QuantizedShapeKeyDeltas = ref ResourceInput_QuantizedShapeKeyDeltas
; Calculate effect of each shapekey of vertex positions (weighted XYZ deltas) and accumulate them as INT32-quantized values.
; Quantization is required to prevent overflow and also benefit from atomic IterlockedAdd which works on integers.
run = CommandListLoadCustomShapeKeysBatch


[CommandList_ShapeKeys_ProcessBatches]
; Calculate effect of each shapekey of vertex positions (XYZ vertex position deltas) and accumulate them as INT32-quantized values.
; Quantization is required to prevent overflow and also benefit from atomic IterlockedAdd which works on integers.
run = CommandList_ShapeKeys_ProcessBatch
; Recursively call this command list again to process the next shapekey batch (if it exists).
$component_shapekey_batch_id = $component_shapekey_batch_id + 1
if $component_shapekey_batch_id < $PoolInput_ShapeKeys_BatchCount[$component_id]
	run = CommandList_ShapeKeys_ProcessBatches
endif


[Constants]
global $component_shapekey_batch_id = 0


; ------------------------------------------------------------------------------
; - DEQUANTIZE VALUES
; ------------------------------------------------------------------------------

[CommandList_ShapeKeys_DequantizeValues]
; Contains position deltas dequantisation scales.
ResourceInput_ShapeKeyBatchConfigs = ref PoolInput_ShapeKeys_BatchConfigs[$component_id]
; Contains per-vertex XYZ positions (mesh geometry).
ResourceInput_VertexPositions = ref PoolInput_ShapeKeys_VertexPositions[$lod_level_uid]
; Contains accumulated INT32-quantized position deltas.
; ResourceInput_QuantizedShapeKeyDeltas = ref Resource_QuantizedShapeKeyDeltasRW
; Stores result of sum of dequantized vertex position deltas of all shapekeys and vertex positions (morphed mesh geometry).
ResourceOutput_ShapeKeyedPositions = ref PoolInput_ShapeKeys_MorphedPositions[$lod_level_uid]
; Dequantize accumulated INT32-quantized position deltas to FLOAT32 and sum them with vertex position buffer.
run = CommandListDequantizeCustomShapeKeys


; ------------------------------------------------------------------------------
; - PROCESS SHAPE KEYS UPDATE
; ------------------------------------------------------------------------------

[CommandList_ProcessShapeKeysUpdate]
; Reset temporary buffer used to accumulate position deltas from multiple shapekeys (and shapekey batches).
clear = ResourceInput_QuantizedShapeKeyDeltas
; Recursively loop through shapekey batches to accumulate INT32-quantized position deltas.
$component_shapekey_batch_id = 0
run = CommandList_ShapeKeys_ProcessBatches
; Dequantize accumulated INT32-quantized position deltas to FLOAT32 and sum them with vertex position buffer.
run = CommandList_ShapeKeys_DequantizeValues


; ------------------------------------------------------------------------------
; - COPY SHAPEKEYED POSITION
; ------------------------------------------------------------------------------

[CommandList_ShapeKeys_CopyShapeKeyedPosition]
ResourceInput_ShapeKeyedPositions = ref PoolInput_ShapeKeys_MorphedPositions[$source_position_uid]
ResourceOutput_ShapeKeyedPositions = ref PoolInput_ShapeKeys_MorphedPositions[$lod_level_uid]
run = CommandListCopyShapeKeyedPosition

; CommandList_ShapeKeys_CopyShapeKeyedPosition INPUT

[Constants]
global $source_position_uid = 0

; ------------------------------------------------------------------------------
; - UPDATE SHAPE KEYS
; ------------------------------------------------------------------------------

[CommandListShapeKeys_Apply]

$lod_level_uid = $component_id * $cfg_sk_max_lod_level_count

; Shape keys recalculation can be skipped if this update was already processed for other lod level.
local $skip_recalculation = 0
if $PoolInput_ShapeKeys_LodPositionCount[$component_id] > 0
    $lod_level_uid = $lod_level_uid + $lod_level
    $skip_recalculation = 1
endif

; ID of last shape key update was requested for this component.
; Set by CommandListSetShapeKey
local $update_id = $PoolInput_ShapeKeys_Component_UpdateId[$component_id]

; ID of last shape key update handled by this lod level of this component.
local $lod_level_last_update_id = $PoolInput_ShapeKeys_LodLevel_LastUpdateId[$lod_level_uid]

; If shape keys update was not yet processed for this lod level...
if $lod_level_last_update_id != $update_id

    ; Setup resources required for shape keys update handling.
    ; Doing it here allows to optimize away dozens of by-ref copies per component per frame.
    run = CommandListCallback_ShapeKeys_AttachComponent

    ; Optimization: re-use already calculated morphed positions from another lod level of this component.
    if $skip_recalculation

        ; Lookup UID of lod level that was last to receive full re-calculation. 
        local $first_updated_lod_level_uid = $PoolInput_ShapeKeys_Component_FirstUpdatedDataIndex[$component_id]

        ; Check if that re-calculation was done for this update...
        if $update_id == $PoolInput_ShapeKeys_LodLevel_LastUpdateId[$first_updated_lod_level_uid]
            ; ... and re-use its results.

            ; Source buffer containing morphed positions computed by the first processed lod.
            $source_position_uid = $first_updated_lod_level_uid

            ; Copy morphed positions from already updated lod level.
            run = CommandList_ShapeKeys_CopyShapeKeyedPosition
        
        else
            
            ; Last re-calculation was done for previous update, so all lod levels have stale morphed positions data.
            $skip_recalculation = 0

        endif

    endif

    ; Re-calculate morphed positions for this component.
    if !$skip_recalculation

        ; Execute expensive morphed positions computations.
        run = CommandList_ProcessShapeKeysUpdate
        
        ; Remember data index of first lod level for which this update was processed first.
        ; It serves as morphed positions copy source for other lod levels.
        $PoolInput_ShapeKeys_Component_FirstUpdatedDataIndex[$component_id] = $lod_level_uid

    endif

    ; Remember ID of last update for this LoD level.
    $PoolInput_ShapeKeys_LodLevel_LastUpdateId[$lod_level_uid] = $update_id

endif

; CommandListShapeKeys_Apply INPUT

[PoolInput_ShapeKeys_Component_UpdateId]
[PoolInput_ShapeKeys_Component_FirstUpdatedDataIndex]
[PoolInput_ShapeKeys_LodLevel_LastUpdateId]

; CommandListShapeKeys_Apply OUTPUT

[Constants]
global $lod_level_uid = 0


; Constants -------------------------

[Constants]

global $shapekey_id = 0
global $shapekey_value = 0

global $shapekey = 0
global $mesh_vertex_count = 0
global $mesh_vertex_offset = 0

global $shapekey_batch_id = 0
global $shapekey_batch_vertex_offset = 0
global $shapekey_batch_vertex_count = 0

global $input_position_stride = 0
global $output_position_stride = 0

global $position_quantization_scale_x = 0
global $position_quantization_scale_y = 0
global $position_quantization_scale_z = 0


; ------------------------------------------------------------------------------
; - SHADER - SHAPE KEY VALUE SETTER
; ------------------------------------------------------------------------------

; Writes custom shape key values to output buffer.
[CustomShaderShapeKeySetter]
; Specify shader.
cs = Shaders/SkapeKeySetter.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0

; Pass INI variables to the shader.
x0 = $shapekey_id
y0 = $shapekey_value

; Pass resources to the shader.
cs-u3 = ref ResourceOutput_ShapeKeyValues
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = 1, 1, 1

; Unbind resources.
cs-u3 = null

; Restore IniParams.
run = CommandListRestoreIniParams0


; ------------------------------------------------------------------------------
; - SHADER - SHAPE KEY LOADER
; ------------------------------------------------------------------------------

; Accumulates INT32-quantized xyz position deltas in output buffer.
[CustomShaderShapeKeyLoader]
; Specify shader.
cs = Shaders/ShapeKeyLoader.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0

; Pass INI variables to the shader.
; * ShapeKeyBatchID
x0 = $shapekey_batch_id

; Pass resources to the shader.
cs-t0 = ref ResourceInput_ShapeKeyBatchConfigs
cs-t1 = ref ResourceInput_ShapeKeyVertexIds
cs-t2 = ref ResourceInput_ShapeKeyVertexOffsets
cs-u3 = ref ResourceInput_ShapeKeyValues
cs-u0 = ref ResourceOutput_QuantizedShapeKeyDeltas
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = ($shapekey_batch_vertex_count+32-1)/32, 1, 1

; Unbind resources.
cs-u0 = null
cs-u3 = null

; Restore IniParams.
run = CommandListRestoreIniParams0


[CommandListLoadCustomShapeKeysBatch]
run = CustomShaderShapeKeyLoader


; ------------------------------------------------------------------------------
; - SHADER - SHAPE KEY DEQUANTIZER
; ------------------------------------------------------------------------------

; Dequantizes INT32-quantized xyz position deltas to FLOAT32.
; Outputs vertex position buffer with applied deltas (morphed mesh).
[CustomShaderShapeKeyDequantizer]
; Specify shader.
cs = Shaders/ShapeKeyDequantizer.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0

; Pass INI variables to the shader.
; * VertexOffset
x0 = $shapekey
; * VertexCount
y0 = $mesh_vertex_count
; * SourceVertexFloatsCount
z0 = $input_position_stride / 4
; * DestinationVertexFloatsCount
w0 = $output_position_stride / 4

; Pass resources to the shader.
cs-t0 = ref ResourceInput_ShapeKeyBatchConfigs
cs-t1 = ref ResourceInput_VertexPositions
cs-u0 = ref ResourceInput_QuantizedShapeKeyDeltas
cs-u2 = ref ResourceOutput_ShapeKeyedPositions
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = ($mesh_vertex_count+64-1)/64, 1, 1

; Unbind resources.
cs-u0 = null
cs-u2 = null

; Restore IniParams.
run = CommandListRestoreIniParams0


[CommandListDequantizeCustomShapeKeys]
$input_position_stride = ResourceInput_VertexPositions->SourceStride
$output_position_stride = ResourceOutput_ShapeKeyedPositions->SourceStride
$shapekey = 0
$mesh_vertex_count = ResourceInput_VertexPositions->Size / $input_position_stride
if $mesh_vertex_count > 0
    run = CustomShaderShapeKeyDequantizer
endif


; ------------------------------------------------------------------------------
; - SHADER - SHAPE KEYED POSITION COPIER
; ------------------------------------------------------------------------------

; Copies float3 vertex positions between buffers with differing strides.
[CustomShaderShapeKeyedPositionCopier]
; Specify shader.
cs = Shaders/ShapeKeyedPositionCopier.hlsl

; Backup IniParams.
; Other mods may use them, so they must be restored after dispatch to avoid conflicts.
run = CommandListBackupIniParams0

; Pass INI variables to the shader.
; * VertexOffset
x0 = $mesh_vertex_offset
; * VertexCount
y0 = $mesh_vertex_count
; * SourceVertexFloatsCount
z0 = $input_position_stride / 4
; * DestinationVertexFloatsCount
w0 = $output_position_stride / 4

; Pass resources to the shader.
cs-t0 = ref ResourceInput_ShapeKeyedPositions
cs-u0 = ref ResourceOutput_ShapeKeyedPositions
; * DebugRW
; cs-u7 = ResourceDebugRW

; Run the compute shader.
dispatch = ($mesh_vertex_count+64-1)/64, 1, 1

; Unbind resources.
cs-u0 = null

; Restore IniParams.
run = CommandListRestoreIniParams0


[CommandListCopyShapeKeyedPosition]
$input_position_stride = ResourceInput_ShapeKeyedPositions->SourceStride
$output_position_stride = ResourceOutput_ShapeKeyedPositions->SourceStride
$mesh_vertex_offset = 0
$mesh_vertex_count = ResourceInput_ShapeKeyedPositions->Size / $input_position_stride
if $mesh_vertex_count > 0
    run = CustomShaderShapeKeyedPositionCopier
endif


; Resources -------------------------

[ResourceInput_ShapeKeyValues]

[ResourceInput_ShapeKeyBatchConfigs]
[ResourceInput_ShapeKeyVertexIds]
[ResourceInput_ShapeKeyVertexOffsets]

[ResourceInput_VertexPositions]
[ResourceInput_QuantizedShapeKeyDeltas]
[ResourceInput_ShapeKeyedPositions]

[ResourceOutput_ShapeKeyValues]
[ResourceOutput_QuantizedShapeKeyDeltas]
[ResourceOutput_ShapeKeyedPositions]
