namespace = EFMIv1


; ------------------------------------------------------------------------------
; - GLOBAL CONFIG CONSTANTS
; ------------------------------------------------------------------------------

[Constants]
global locked $cfg_spatial_base_radius = 3
global locked $cfg_spatial_expiration_frames = 1
global locked $cfg_spatial_expiration_reset = 1
global locked $cfg_spatial_expiration_read_refresh = 1
global locked $cfg_spatial_detault_value = 0
global locked $cfg_spatial_instance_load_ratio = 4

global locked $cfg_spatial_max_instance_count = 32
global locked $cfg_spatial_cell_size = 0.125


; ------------------------------------------------------------------------------
; - API
; ------------------------------------------------------------------------------

[Constants]
global locked $enum_object_status_custom  = 0b111111111111111111111111
global locked $enum_object_status_unknown = 0b111111111111111111111110

global locked $enum_override_type_skip     = 1
global locked $enum_override_type_original = 2
global locked $enum_override_type_custom   = 3


[CommandListSpatialIdentity_IdentifyComponentInstances]
; Assign id to this call.
run = CommandList_SpatialIdentity_IdentifyCaller
; Reset draw call descriptors.
$draw_call_has_unknown_instance = 0
$draw_call_has_modded_instance = 0
; Callback to `run` for each instance, each has $draw_call_instance_id incremented by 1 (starts with 0 for each CommandListIterateInstances call).
CommandListCallback_OnInstance = ref CommandListSpatialIdentity_IdentifyObject
; Call per-draw-instance iteration helper.
run = CommandListIterateInstances


; CommandListSpatialIdentity INPUT

[PoolInput_ObjectSpatialIdentity]

[Constants]
global $identification_min_components = 4
global $identification_timeout_frames = 255


; CommandListSpatialIdentity OUTPUT

[PoolSpatialIdentity_SpatialIds]
pool_size = $cfg_spatial_max_instance_count

[PoolSpatialIdentity_IdentifiedInstances]
pool_size = $cfg_spatial_max_instance_count

[Constants]
global $draw_call_has_modded_instance = 0
global $draw_call_has_unknown_instance = 0


; ------------------------------------------------------------------------------
; - CALLER IDENTIFICATION
; ------------------------------------------------------------------------------

[Constants]
global $last_draw_call_number = 0
global $identifier_call_number = 0


[CommandList_SpatialIdentity_IdentifyCaller]
; Assign unique ID to each caller within the same draw call.
; We need this because we want only the first caller mod to draw non-modded instances.
if $last_draw_call_number != DRAW_NUMBER
    $last_draw_call_number = DRAW_NUMBER
    $identifier_call_number = 0
else
    $identifier_call_number = $identifier_call_number + 1
endif


; ------------------------------------------------------------------------------
; - OUTPUT INTERFACE SETTERS
; ------------------------------------------------------------------------------

[CommandList_SpatialIdentity_SetOutput_SpatialId]
$PoolSpatialIdentity_SpatialIds[$draw_call_instance_id] = PoolInput_ObjectSpatialIdentity[$spatial_hash]->Index


[CommandList_SpatialIdentity_SetOutput_ObjectStatus_Custom]
$PoolSpatialIdentity_IdentifiedInstances[$draw_call_instance_id] = $enum_override_type_custom


[CommandList_SpatialIdentity_SetOutput_ObjectStatus_Original]
$PoolSpatialIdentity_IdentifiedInstances[$draw_call_instance_id] = $enum_override_type_original


[CommandList_SpatialIdentity_SetOutput_ObjectStatus_Skip]
$PoolSpatialIdentity_IdentifiedInstances[$draw_call_instance_id] = $enum_override_type_skip


[CommandList_SpatialIdentity_SetOutput_Custom]
$draw_call_has_modded_instance = 1
; Return assigned slot of temporal position tracker as stable "Spatial ID".
run = CommandList_SpatialIdentity_SetOutput_SpatialId
; Signal caller mod to override this instance with custom draw call.
run = CommandList_SpatialIdentity_SetOutput_ObjectStatus_Custom


[CommandListSpatialIdentity_SetOutput_Unknown]
$draw_call_has_unknown_instance = 1
; Return assigned slot of temporal position tracker as stable "Spatial ID".
run = CommandList_SpatialIdentity_SetOutput_SpatialId
; Split instanced draw between mods.
if $identifier_call_number == 0
    ; Signal the first caller mod to use original draw call for this instance.
    run = CommandList_SpatialIdentity_SetOutput_ObjectStatus_Original
else
    ; Signal other caller mods to completely skip this instance.
    run = CommandList_SpatialIdentity_SetOutput_ObjectStatus_Skip
endif


[CommandListSpatialIdentity_SetOutput_Skip]
$draw_call_has_unknown_instance = 1
; Return assigned slot of temporal position tracker as stable "Spatial ID".
run = CommandList_SpatialIdentity_SetOutput_SpatialId
; Signal other caller mods to completely skip this instance.
run = CommandList_SpatialIdentity_SetOutput_ObjectStatus_Skip


; ------------------------------------------------------------------------------
; - OBJECT IDENTIFICATION
; ------------------------------------------------------------------------------

[Constants]
global $spatial_hash = 0
global $object_status_bitmask = 0
global $frame_distance = 0


[CommandListSpatialIdentity_IdentifyObject]
; ->SpatialHash expects offsets in `value` units. Instance config consists of 16 CB "constant" units of 4 `value` units each.
local $instance_offset = $draw_call_instance_id * 64
$spatial_hash = ResourceOriginal_VS_CB->SpatialHash($instance_offset + 12, $instance_offset + 13, $instance_offset + 14, $cfg_spatial_cell_size)

; Get object spatial identification status bitmask from the pool.
; Stores the whole identification process state in a single variable.
$object_status_bitmask = $PoolInput_ObjectSpatialIdentity[$spatial_hash]

if $object_status_bitmask == $enum_object_status_custom
    ; Identified as Custom.
    ; Hot path for objects that are already confirmed to require overriding by the caller mod.
    run = CommandList_SpatialIdentity_SetOutput_Custom

else if $object_status_bitmask == $enum_object_status_unknown
    ; Identified as Unknown.
    ; Not-so-hot path for objects that are already confirmed to require skipping by the caller mod.
    ; Some components (e.g. shadow meshes) are shared between different objects, and this one happens to be such an object.
    run = CommandListSpatialIdentity_SetOutput_Unknown

else
    ; Identification Ongoing.
    run = CommandList_SpatialIdentity_AdvanceOngoingIdentification

endif

; Attach spatial debugger.
; $enable_spatial_debugger = 1
; if $enable_spatial_debugger
;     run = CommandListSpatialIdentity_AttachDebugger
; endif


; ------------------------------------------------------------------------------
; - OBJECT STATUS BITMASK UPDATE
; ------------------------------------------------------------------------------

[CommandList_SpatialIdentity_AdvanceOngoingIdentification]
; Object identification completes as:
; 1. "Identified as Custom" when:
;   * Count of `1` bits in `ComponentFlags` bitmask region is above or equal to $identification_min_components.
;   * At least 1 frame passed since the `FrameSnapshot` bitmask region.
; 2. "Identified as Unknown" when:
;   * $identification_timeout_frames frames passed since the `FrameSnapshot` bitmask region and object is still not identified.

; Bitmask State Transitions
;
;        Empty
;          │
;          ▼
;    Tracking (frame snapshot + component mask)
;      │                     │
;      │ enough components   │ timeout (8 frames)
;      ▼                     ▼
;    Custom               Unknown

; Number of frames between snapshots. Wraps around 16.
$frame_distance = 0

; Update tracking state.
run = CommandList_SpatialIdentity_UpdateObjectStatusBitmask

; Decide how to treat this instance.
if $frame_distance == 0
    ; This spatial identity just appeared.
    ; Delay the first draw of object with this spatial identity by 1 frame.
    ; For per-component skeleton it'll give us a 1-frame leeway to complete spatial identification.
    ; For merged skeleton it'll also allow us to capture bones from all components before the first usage.

    ; Signal mod to skip drawing this instance.
    run = CommandListSpatialIdentity_SetOutput_Skip
else
    ; At least 1 frame passed since the first appearence of this spatial identity.
    ; We can't allow ourselves to delay the first draw any longer, so must decide here.

    ; Here we count the number of lower 16 bits set. Each set bit represents detected component.
    ; Components with ids are wrapped around 16, so detected Component 16 sets the same bit as Component 0.
    if countbits($object_status_bitmask & 0xFFFF) >= $identification_min_components
        ; Identified as Custom. 
        $PoolInput_ObjectSpatialIdentity[$spatial_hash] = $enum_object_status_custom
        
        ; Signal mod to draw this instance with modded assets and custom draw calls.
        run = CommandList_SpatialIdentity_SetOutput_Custom

    else
        
        if $frame_distance >= $identification_timeout_frames
            ; Identified as Unknown.
            $PoolInput_ObjectSpatialIdentity[$spatial_hash] = $enum_object_status_unknown
        endif

        ; Signal mod to draw this instance with original assets and original draw call.
        run = CommandListSpatialIdentity_SetOutput_Unknown

    endif

endif


; ------------------------------------------------------------------------------
; - OBJECT STATUS BITMASK UPDATE
; ------------------------------------------------------------------------------

[CommandList_SpatialIdentity_UpdateObjectStatusBitmask]
; Bitmask Layout:
;
; 00000000 00000000 00000000 00000000
; ^^^^^^^^ ^^^^^^^^ ^^^^^^^^ ^^^^^^^^
; ^- N/A   ^        ^--------^- ComponentFlags
;          ^- FrameSnapshot
;
; Possible states:
; 1. Identified as Custom: Equals $enum_object_status_custom if object is confirmed to be the modded one.
; 2. Identified as Unknown: Equals $enum_object_status_unknown if object is confirmed NOT to be the modded one.
; 3. Identification Ongoing: Uses complex bitmask for ongoing identification:
;   3.1. Upper 8 bits are unavailable due to precision loss from float conversion.
;   3.2. Middle 8 bits reserved for first object encounter frame snapshot (remainder from division of frame number by 256).
;   3.3. Lower 16 bits reserved for "first encounter" state flags for object's components (components ids are wrapped around 16).

; Collapse frame number to 8-bit space. Equals to `FRAME_NUMBER % 256` but faster.
local $current_frame_modulo = FRAME_NUMBER & 0xFF

if $object_status_bitmask == 0
    ; Snapshot current frame to empty bitmask.
    $object_status_bitmask = $object_status_bitmask | ($current_frame_modulo << 16)
else
    ; Extract frame snapshot from bitmsk.
    local $snapshot_frame_modulo = ($object_status_bitmask >> 16) & 0xFF
    ; Number of frames passed between snapshots. Wraps around 256.
    $frame_distance = ($current_frame_modulo - $snapshot_frame_modulo) & 0xFF
endif

; Update corresponding component's bit in bitmask. Wrap $component_id around 16.
local $component_seen_bit = 1 << ($component_id & 0xF)
if ($object_status_bitmask & $component_seen_bit) == 0
    ; Set corresponding component's bit in bitmask to 1.
    $object_status_bitmask = $object_status_bitmask | $component_seen_bit
    ; Save updated bitmask to the pool.
    $PoolInput_ObjectSpatialIdentity[$spatial_hash] = $object_status_bitmask
endif


; ------------------------------------------------------------------------------
; - SPATIAL DEBUGGER
; ------------------------------------------------------------------------------

[Constants]
global $enable_spatial_debugger = 0
global $spatial_debugger_component_id = 0
global $spatial_hashes_count = 4
global $x = 0
global $y = 0
global $z = 0


[Pool_SpatialDebug]
pool_index_type = spatial
pool_size = $spatial_hashes_count
pool_spatial_radius = $cfg_spatial_base_radius
pool_expiration_timeout_frames = $cfg_spatial_expiration_frames
pool_expiration_reset_elements = $cfg_spatial_expiration_reset
pool_expiration_refresh_on_read = $cfg_spatial_expiration_read_refresh
pool_allocate_slot_on_missing = 1


[Pool_SpatialDebugData]
pool_size = $spatial_hashes_count * 4
pool_variable_default_value = 0
pool_expiration_timeout_frames = $cfg_spatial_expiration_frames
pool_expiration_reset_elements = $cfg_spatial_expiration_reset


[CommandListSpatialIdentity_AttachDebugger]
if $component_id == $spatial_debugger_component_id
    store = $x, Resource_Component_Instance_ConfigRW, 12
    store = $y, Resource_Component_Instance_ConfigRW, 13
    store = $z, Resource_Component_Instance_ConfigRW, 14
    local $base_index = Pool_SpatialDebug[$spatial_hash]->Index * 4
    $Pool_SpatialDebugData[$base_index + 0] = $spatial_hash
    $Pool_SpatialDebugData[$base_index + 1] = $x
    $Pool_SpatialDebugData[$base_index + 2] = $y
    $Pool_SpatialDebugData[$base_index + 3] = $z
endif


[Present]
if $enable_spatial_debugger
    x100 = $Pool_SpatialDebugData[0]
    y100 = $Pool_SpatialDebugData[1]
    z100 = $Pool_SpatialDebugData[2]
    w100 = $Pool_SpatialDebugData[3]

    x101 = $Pool_SpatialDebugData[4]
    y101 = $Pool_SpatialDebugData[5]
    z101 = $Pool_SpatialDebugData[6]
    w101 = $Pool_SpatialDebugData[7]

    x102 = $Pool_SpatialDebugData[8]
    y102 = $Pool_SpatialDebugData[9]
    z102 = $Pool_SpatialDebugData[10]
    w102 = $Pool_SpatialDebugData[11]

    x103 = $Pool_SpatialDebugData[12]
    y103 = $Pool_SpatialDebugData[13]
    z103 = $Pool_SpatialDebugData[14]
    w103 = $Pool_SpatialDebugData[15]
endif
